"""baseline

Revision ID: 8f9ec6c7693a
Revises: 
Create Date: 2025-08-16 02:23:34.915432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f9ec6c7693a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('categories', 'slug',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=160),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('categories', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_categories_description'), 'categories', ['description'], unique=False)
    op.alter_column('otps', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=254),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('posts', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_posts_category_id'), 'posts', ['category_id'], unique=False)
    op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_category_id'), table_name='posts')
    op.drop_column('posts', 'category_id')
    op.alter_column('otps', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=254),
               existing_nullable=False)
    op.drop_index(op.f('ix_categories_description'), table_name='categories')
    op.alter_column('categories', 'description',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(collation='utf8mb4_general_ci'),
               existing_nullable=True)
    op.alter_column('categories', 'slug',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=160),
               existing_nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=120),
               existing_nullable=False)
    # ### end Alembic commands ###
